// <auto-generated />
using System;
using MgrAngularWithDockers.Models.db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MgrAngularWithDockers.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200314153859_testresultChange")]
    partial class testresultChange
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MgrAngularWithDockers.Models.Test", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<int>("Iterations")
                        .HasColumnType("int");

                    b.Property<string>("TestNamespace")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Guid");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("MgrAngularWithDockers.Models.TestResult", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Result")
                        .HasColumnType("int");

                    b.Property<Guid>("TestGuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Guid");

                    b.HasIndex("TestGuid")
                        .IsUnique();

                    b.ToTable("TestResults");
                });

            modelBuilder.Entity("MgrAngularWithDockers.Models.TestResult", b =>
                {
                    b.HasOne("MgrAngularWithDockers.Models.Test", "Test")
                        .WithOne("TestResult")
                        .HasForeignKey("MgrAngularWithDockers.Models.TestResult", "TestGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
